### ISSUE TITLE
Make pre-trained checkpoints available

### ISSUE THREAD

**Issue by wtriple** [fakufaku/diffusion-separation#1]
Dear author, hello! Would it be possible for me to have the privilege of obtaining your pre-trained weights? I've tried running your code, but due to limitations in computational resources, it may take a long time to complete training and may not achieve the results reported in your paper.

**Comment by fakufaku** [comment]
Hi @WuWenwei0206 

It would indeed be nice to make checkpoints available. I will look into it, but cannot promise to do it quickly.

**Comment by fakufaku** [comment]
@WuWenwei0206 I took some time but I have released the checkpoint used for separation in the paper. I have also added a script (`separate.py`) to make it easy to use. Hope this is still helpful!
