### ISSUE TITLE
Clarification Regarding Default Parameters in Relation to Paper Results

### ISSUE THREAD

**Issue by wres168** [fakufaku/diffusion-separation#2]
Hello,

I am reaching out to gain a better understanding of the default parameters specified in this repository. I would like to know if the default parameters set in the code are the ones that correspond to the optimal results mentioned in the paper.

Could you please clarify if any adjustments are needed to replicate the results mentioned in the paper, or if the default settings are indeed the configurations that yielded the best results?

I appreciate your time and effort in maintaining this repository and look forward to your response.

Thank you!

**Comment by fakufaku** [comment]
Hello @wres168 , the config files
```
config/experiment/icassp-separation.yaml
config/experiment/noise-reduction.yaml
```
should run training with the same parameters used in the paper.
If you follow the instructions in the [README](https://github.com/fakufaku/diffusion-separation#enhancement), you should be able to get the same results as the paper.
